### ISSUE TITLE
Fail to load model

### ISSUE THREAD

**Issue by VimalrajXy** [ydwen/opensphere#28]
Traceback (most recent call last):
  File "C:\Users\Vimalraj\PycharmProjects\Opensphere\main_inference.py", line 34, in <module>
    model = Model(config['model'])
  File "C:\Users\Vimalraj\PycharmProjects\Opensphere\opensphere\model.py", line 25, in __init__
    self.backbone = self.build_module(args['backbone']['net']).to(self.rank)
  File "C:\Users\Vimalraj\PycharmProjects\Opensphere\opensphere\model.py", line 33, in build_module
    return build_from_args(args, 'opensphere.module')
  File "C:\Users\Vimalraj\PycharmProjects\Opensphere\opensphere\utils\build_helper.py", line 23, in build_from_args
    return obj_cls(**args)
  File "C:\Users\Vimalraj\PycharmProjects\Opensphere\opensphere\module\backbone\sfnet.py", line 253, in sfnet20
    return _sfnet('sfnet20', BasicBlock, [1, 2, 4, 1], pretrained, progress,
  File "C:\Users\Vimalraj\PycharmProjects\Opensphere\opensphere\module\backbone\sfnet.py", line 215, in _sfnet
    model = SFNet(block, layers, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'out_channel'

**Comment by ydwen** [comment]
Hi VimalrajXy. We rename 'out_channel' as 'embed_dim' in our new commit.
